// ═══════════════════════════════════════════════════════════════
// SYSTEM LEVELING — Default Data Generator
// Creates initial quests, titles, inventory after onboarding
// ═══════════════════════════════════════════════════════════════

import type {
  Quest, Title, InventoryItem, UserProfile, StatKey,
  CharacterStats, ClassName,
} from './Types';
import { generateId } from './Storage';
import { getExpToNextLevel } from './GameData';

// ═══ CREATE DEFAULT USER FROM ONBOARDING ═══
export function createUserFromOnboarding(
  nickname: string,
  stats: Record<StatKey, number>,
  className: ClassName = 'warrior',
): UserProfile {
  return {
    id: generateId(),
    nickname,
    avatarUri: null,
    className,
    level: 1,
    currentExp: 0,
    expToNextLevel: getExpToNextLevel(1),
    gold: 100,
    gems: 5,
    equippedTitleId: 'title-newbie',
    stats: stats as CharacterStats,
    debtPoints: 0,
    streakDays: 0,
    totalQuestsCompleted: 0,
    dateOfBirth: null,
    gender: null,
    heightCm: null,
    weightKg: null,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };
}

// ═══ DAILY QUEST TEMPLATES ═══
export function generateDailyQuests(): Quest[] {
  const today = Date.now();
  const quests: Quest[] = [
    {
      id: generateId(),
      title: 'Uống nước buổi sáng',
      description: 'Uống 500ml nước ấm ngay khi thức dậy',
      type: 'daily',
      difficulty: 'E',
      category: 'health',
      date: today,
      timeWindow: { start: '06:00', end: '07:00', durationMinutes: 5 },
      subtasks: ['Chuẩn bị ly nước', 'Uống hết 500ml'],
      rewards: { exp: 30, gold: 5, skillPoints: [], itemDrop: null },
      penaltyOnFail: { expLoss: 0, debtPoints: 0 },
      relatedGoalId: null,
      relatedSkillIds: [],
      status: 'pending',
      completedAt: null,
      createdAt: today,
    },
    {
      id: generateId(),
      title: 'Morning Workout',
      description: 'Tập thể dục buổi sáng 30 phút',
      type: 'daily',
      difficulty: 'C',
      category: 'fitness',
      date: today,
      timeWindow: { start: '06:30', end: '07:30', durationMinutes: 30 },
      subtasks: ['Khởi động 5 phút', 'Bài tập chính 20 phút', 'Giãn cơ 5 phút'],
      rewards: { exp: 150, gold: 10, skillPoints: [], itemDrop: null },
      penaltyOnFail: { expLoss: 30, debtPoints: 1 },
      relatedGoalId: null,
      relatedSkillIds: [],
      status: 'pending',
      completedAt: null,
      createdAt: today,
    },
    {
      id: generateId(),
      title: 'Deep Focus Session',
      description: 'Học tập/làm việc tập trung 2 giờ không gián đoạn',
      type: 'daily',
      difficulty: 'B',
      category: 'learning',
      date: today,
      timeWindow: { start: '08:00', end: '12:00', durationMinutes: 120 },
      subtasks: ['Xác định mục tiêu', 'Pomodoro 4x25min', 'Note kết quả'],
      rewards: { exp: 250, gold: 15, skillPoints: [], itemDrop: null },
      penaltyOnFail: { expLoss: 50, debtPoints: 1 },
      relatedGoalId: null,
      relatedSkillIds: [],
      status: 'pending',
      completedAt: null,
      createdAt: today,
    },
    {
      id: generateId(),
      title: 'Đọc sách 30 phút',
      description: 'Đọc ít nhất 20 trang sách',
      type: 'daily',
      difficulty: 'D',
      category: 'learning',
      date: today,
      timeWindow: { start: '12:00', end: '14:00', durationMinutes: 30 },
      subtasks: ['Chọn sách', 'Đọc 20+ trang', 'Ghi chú ý chính'],
      rewards: { exp: 80, gold: 8, skillPoints: [], itemDrop: null },
      penaltyOnFail: { expLoss: 0, debtPoints: 0 },
      relatedGoalId: null,
      relatedSkillIds: [],
      status: 'pending',
      completedAt: null,
      createdAt: today,
    },
    {
      id: generateId(),
      title: 'Vocabulary Builder',
      description: 'Học 15 từ vựng mới + ôn lại 30 từ cũ',
      type: 'daily',
      difficulty: 'D',
      category: 'language',
      date: today,
      timeWindow: { start: '14:00', end: '15:00', durationMinutes: 30 },
      subtasks: ['Học 15 từ mới', 'Ôn 30 từ cũ', 'Viết câu mẫu'],
      rewards: { exp: 80, gold: 8, skillPoints: [], itemDrop: null },
      penaltyOnFail: { expLoss: 0, debtPoints: 0 },
      relatedGoalId: null,
      relatedSkillIds: [],
      status: 'pending',
      completedAt: null,
      createdAt: today,
    },
    {
      id: generateId(),
      title: 'Code Practice',
      description: 'Giải 2 bài coding challenge hoặc làm project',
      type: 'daily',
      difficulty: 'C',
      category: 'tech',
      date: today,
      timeWindow: { start: '15:00', end: '17:00', durationMinutes: 60 },
      subtasks: ['Chọn bài/project', 'Code solution', 'Test & review'],
      rewards: { exp: 180, gold: 12, skillPoints: [], itemDrop: null },
      penaltyOnFail: { expLoss: 30, debtPoints: 1 },
      relatedGoalId: null,
      relatedSkillIds: [],
      status: 'pending',
      completedAt: null,
      createdAt: today,
    },
    {
      id: generateId(),
      title: 'Financial Check-in',
      description: 'Ghi nhận chi tiêu trong ngày',
      type: 'daily',
      difficulty: 'E',
      category: 'finance',
      date: today,
      timeWindow: { start: '20:00', end: '21:00', durationMinutes: 10 },
      subtasks: ['Mở app Finance', 'Ghi tất cả giao dịch'],
      rewards: { exp: 30, gold: 10, skillPoints: [], itemDrop: null },
      penaltyOnFail: { expLoss: 0, debtPoints: 0 },
      relatedGoalId: null,
      relatedSkillIds: [],
      status: 'pending',
      completedAt: null,
      createdAt: today,
    },
    {
      id: generateId(),
      title: 'Evening Reflection',
      description: 'Viết nhật ký cuối ngày & đánh giá',
      type: 'daily',
      difficulty: 'E',
      category: 'wellness',
      date: today,
      timeWindow: { start: '21:00', end: '22:00', durationMinutes: 15 },
      subtasks: ['Viết 3 điều biết ơn', 'Đánh giá ngày hôm nay', 'Kế hoạch ngày mai'],
      rewards: { exp: 20, gold: 5, skillPoints: [], itemDrop: null },
      penaltyOnFail: { expLoss: 0, debtPoints: 0 },
      relatedGoalId: null,
      relatedSkillIds: [],
      status: 'pending',
      completedAt: null,
      createdAt: today,
    },
  ];
  return quests;
}

// ═══ DEFAULT TITLES ═══
export function getDefaultTitles(): Title[] {
  return [
    {
      id: 'title-newbie',
      name: 'Tân Binh',
      nameEn: 'Newbie',
      description: 'Bắt đầu hành trình với Hệ Thống',
      condition: 'Hoàn thành Onboarding',
      rarity: 'common',
      iconEmoji: '🌱',
      isUnlocked: true,
      unlockedAt: Date.now(),
      category: 'milestone',
    },
    {
      id: 'title-first-quest',
      name: 'Kẻ Thực Thi',
      nameEn: 'The Executor',
      description: 'Hoàn thành quest đầu tiên',
      condition: 'Hoàn thành 1 quest',
      rarity: 'common',
      iconEmoji: '⚔️',
      isUnlocked: false,
      unlockedAt: null,
      category: 'quest',
    },
    {
      id: 'title-streak-3',
      name: 'Kẻ Kiên Trì',
      nameEn: 'Persistent One',
      description: '3 ngày liên tiếp hoàn thành quest',
      condition: 'Streak 3 ngày',
      rarity: 'uncommon',
      iconEmoji: '🔥',
      isUnlocked: false,
      unlockedAt: null,
      category: 'streak',
    },
    {
      id: 'title-streak-7',
      name: 'Kẻ Nỗ Lực Không Ngừng',
      nameEn: 'Relentless',
      description: '7 ngày liên tiếp',
      condition: 'Streak 7 ngày',
      rarity: 'rare',
      iconEmoji: '💫',
      isUnlocked: false,
      unlockedAt: null,
      category: 'streak',
    },
    {
      id: 'title-streak-30',
      name: 'Shadow Monarch',
      nameEn: 'Shadow Monarch',
      description: '30 ngày liên tiếp không nghỉ',
      condition: 'Streak 30 ngày',
      rarity: 'legendary',
      iconEmoji: '👑',
      isUnlocked: false,
      unlockedAt: null,
      category: 'streak',
    },
    {
      id: 'title-level-5',
      name: 'Chiến Binh Trẻ',
      nameEn: 'Young Warrior',
      description: 'Đạt Level 5',
      condition: 'Level 5',
      rarity: 'common',
      iconEmoji: '🗡️',
      isUnlocked: false,
      unlockedAt: null,
      category: 'level',
    },
    {
      id: 'title-level-10',
      name: 'Kẻ Đáng Gờm',
      nameEn: 'Formidable',
      description: 'Đạt Level 10',
      condition: 'Level 10',
      rarity: 'uncommon',
      iconEmoji: '⚡',
      isUnlocked: false,
      unlockedAt: null,
      category: 'level',
    },
    {
      id: 'title-level-25',
      name: 'Huyền Thoại Sống',
      nameEn: 'Living Legend',
      description: 'Đạt Level 25',
      condition: 'Level 25',
      rarity: 'epic',
      iconEmoji: '🌟',
      isUnlocked: false,
      unlockedAt: null,
      category: 'level',
    },
    {
      id: 'title-quest-10',
      name: 'Thợ Săn Chăm Chỉ',
      nameEn: 'Diligent Hunter',
      description: 'Hoàn thành 10 quests',
      condition: '10 quests completed',
      rarity: 'uncommon',
      iconEmoji: '🎯',
      isUnlocked: false,
      unlockedAt: null,
      category: 'quest',
    },
    {
      id: 'title-quest-50',
      name: 'Sát Thủ Nhiệm Vụ',
      nameEn: 'Quest Slayer',
      description: 'Hoàn thành 50 quests',
      condition: '50 quests completed',
      rarity: 'rare',
      iconEmoji: '💀',
      isUnlocked: false,
      unlockedAt: null,
      category: 'quest',
    },
    {
      id: 'title-bookworm',
      name: 'Mọt Sách',
      nameEn: 'Bookworm',
      description: 'Đọc 10 cuốn sách trong Library',
      condition: '10 books read',
      rarity: 'rare',
      iconEmoji: '📚',
      isUnlocked: false,
      unlockedAt: null,
      category: 'learning',
    },
    {
      id: 'title-finance-guru',
      name: 'Bậc Thầy Tài Chính',
      nameEn: 'Finance Guru',
      description: 'Tiết kiệm được 1 triệu đồng',
      condition: 'Save 1M',
      rarity: 'epic',
      iconEmoji: '💰',
      isUnlocked: false,
      unlockedAt: null,
      category: 'finance',
    },
  ];
}

// ═══ STARTER INVENTORY ═══
export function getStarterInventory(): InventoryItem[] {
  return [
    {
      id: generateId(),
      name: 'Bình Nước Tân Binh',
      description: 'Một bình nước đơn giản. Nhắc nhở bạn uống đủ nước mỗi ngày.',
      iconName: '🧴',
      rarity: 'common',
      category: 'equipment',
      quantity: 1,
      obtainedAt: Date.now(),
      questId: null,
    },
    {
      id: generateId(),
      name: 'Sổ Tay Lữ Khách',
      description: 'Cuốn sổ ghi chép hành trình. Mở khóa tính năng Journal.',
      iconName: '📓',
      rarity: 'common',
      category: 'key_item',
      quantity: 1,
      obtainedAt: Date.now(),
      questId: null,
    },
    {
      id: generateId(),
      name: 'Potion EXP x2 (1h)',
      description: 'Nhân đôi EXP nhận được trong 1 giờ.',
      iconName: '🧪',
      rarity: 'uncommon',
      category: 'consumable',
      quantity: 3,
      obtainedAt: Date.now(),
      questId: null,
    },
  ];
}
